import { type NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import Image from "next/image"
import { api } from "~/utils/api"

const ProfilePage: NextPage = () => {
  const router = useRouter()
  const { slug, authorId } = router.query
  if (typeof authorId !== "string") return <div>An error has occurred</div>
  if (typeof slug !== "string") return <div>An error has occurred</div>
  const { data: postsByUser, isLoading } = api.main.getAllByUser.useQuery({
    authorId: authorId,
  })
  return (
    <>
      <Head>
        <title>{slug.substring(1)} Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-start justify-start">
        <figure className="flex h-48 w-full items-end bg-blue-300">
          <Image
            src={postsByUser?.author.profileImageUrl ?? "/user.svg"}
            alt="profile-image"
            width={64}
            height={64}
            className="relative left-4 top-8 rounded-full"
          />
        </figure>
        <h1 className="mt-12 w-full border-b border-b-[#ffffff50] pb-3 pl-3 text-xl font-bold">
          @{postsByUser?.author.username}
        </h1>
        {isLoading ? (
          <div>Loading...</div>
        ) : (
          <ul>
            {postsByUser?.posts.map((el) => (
              <li key={el.id}>{el.content}</li>
            ))}
          </ul>
        )}
      </main>
    </>
  )
}
export default ProfilePage
