import { type AppType } from "next/app"
import { api } from "~/utils/api"
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "react-hot-toast"
import "~/styles/globals.css"
import Head from "next/head"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <ClerkProvider {...pageProps}>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ReactQueryDevtools initialIsOpen={false} /> */}
      <Toaster position="bottom-center" reverseOrder={false} />
      <Component {...pageProps} />
    </ClerkProvider>
  )
}

export default api.withTRPC(MyApp)
