import { type NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { api } from "~/utils/api"
import Post from "~/components/Post"

const SinglePostPage: NextPage = () => {
  const router = useRouter()
  const { id, authorId } = router.query
  if (typeof id !== "string") return <div></div>
  if (typeof authorId !== "string") return <div></div>
  const { data, isLoading } = api.main.getPostById.useQuery({
    postId: id,
    authorId,
  })
  if (isLoading) return <div>Loading...</div>
  if (!data) return <div>Error! No data</div>
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Post post={data?.post} author={data?.author} />
      </main>
    </>
  )
}
export default SinglePostPage
